builds:
  - binary: maze
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: maze
    homepage: https://github.ibm.com/MAZE-MultiCloud/maze-cli
    tap:
      owner: maze
      name: homebrew-maze-cli
    commit_author:
      name: maze
      email: developer@maze-multicloud.co.uk
checksum:
  name_template: 'checksums.txt'