# .travis.yml
language: go

go:
- 1.x

script:
  - go test -v ./...

jobs:
  include:
  - stage: deploy
    if: tag IS present

install: true
# calls goreleaser
deploy:
- provider: script
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  script: curl -sfL https://goreleaser.com/static/run | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

notifications:
  email:
    recipients:
      - admin@maze-multicloud.com
    on_success: always
    on_failure: always
