# .travis.yml
language: go

script:
  - curl -sfL https://goreleaser.com/static/run | bash -s -- check # check goreleaser config for deprecations

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sfL https://goreleaser.com/static/run | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

notifications:
  email:
    recipients:
      - admin@maze-multicloud.com
    on_success: always
    on_failure: always
